/** Admin moderation queue for verified product and overall-order reviews. */
import { useCallback, useEffect, useMemo, useState } from "react";
import { deleteAdminReview, getAdminReviews, updateAdminReview } from "../../services/adminApi.js";
import AdminPageHeader from "../../components/admin/AdminPageHeader.jsx";
import AdminStatus from "../../components/admin/AdminStatus.jsx";
import AdminExportMenu from "../../components/admin/AdminExportMenu.jsx";

export default function AdminReviews(){
 const [data,setData]=useState({productReviews:[],orderReviews:[]}); const [status,setStatus]=useState(""); const [message,setMessage]=useState("");
 const load=useCallback(async()=>{try{setMessage("");const r=await getAdminReviews({status});setData(r.data||{productReviews:[],orderReviews:[]})}catch(e){setMessage(e.message)}},[status]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{const handler=(e)=>{if(e.detail?.event?.startsWith("review:"))load();};window.addEventListener("beyonist:admin-realtime",handler);return()=>window.removeEventListener("beyonist:admin-realtime",handler)},[load]);
 const rows=useMemo(()=>[...(data.productReviews||[]).map(r=>({...r,type:"product"})),...(data.orderReviews||[]).map(r=>({...r,type:"order"}))],[data]);
 async function moderate(review,next){try{await updateAdminReview(review.type,review._id,next);await load()}catch(e){setMessage(e.message)}}
 async function remove(review){if(!window.confirm("Delete this review permanently?"))return;try{await deleteAdminReview(review.type,review._id);await load()}catch(e){setMessage(e.message)}}
 const columns=[{label:"Type",value:"type"},{label:"Customer",value:r=>r.customer?.name||r.displayName},{label:"Order",value:"orderNumber"},{label:"Product",value:r=>r.productName||"Overall order"},{label:"Rating",value:"rating"},{label:"Status",value:"status"},{label:"Review",value:"body"},{label:"Created",value:r=>new Date(r.createdAt).toLocaleString("en-IN")}];
 return <><AdminPageHeader eyebrow="Customer voice / Reviews" title="Verified reviews." copy="Moderate product reviews and overall order testimonials submitted only after a verified delivery." action={<select value={status} onChange={e=>setStatus(e.target.value)} className="border border-black/10 bg-[#f7f3ed] px-4 py-3 text-[8px] uppercase"><option value="">All reviews</option><option value="pending">Pending</option><option value="published">Published</option><option value="rejected">Rejected</option></select>}/><AdminExportMenu title="Reviews" columns={columns} rows={rows}/>{message?<p className="mb-4 text-[9px] text-[#cf1f2e]">{message}</p>:null}<div className="grid grid-cols-2 gap-4 max-[850px]:grid-cols-1">{rows.map(review=><article key={`${review.type}-${review._id}`} className="border border-black/10 bg-[#f7f3ed] p-5"><div className="flex items-start justify-between gap-4"><div><span className="text-[6px] uppercase tracking-[.14em] text-[#cf1f2e]">{review.type==="product"?`Product · ${review.productName}`:"Overall order"}</span><strong className="mt-2 block font-[Georgia] text-[24px] font-normal">{review.displayName||review.customer?.name||"Verified customer"}</strong></div><AdminStatus value={review.status}/></div><div className="mt-4 text-[18px] text-[#fbbc04]">{"★".repeat(review.rating)}<span className="text-black/15">{"★".repeat(5-review.rating)}</span></div><strong className="mt-3 block font-[Georgia] text-[20px] font-normal">{review.title||review.orderNumber}</strong><p className="mt-2 text-[9px] leading-5 text-black/65">{review.body}</p><div className="mt-5 flex flex-wrap gap-2 border-t border-black/10 pt-4"><button type="button" onClick={()=>moderate(review,"published")} className="bg-black px-3 py-2 text-[7px] uppercase tracking-[.1em] text-white">Publish</button><button type="button" onClick={()=>moderate(review,"rejected")} className="border border-black/10 px-3 py-2 text-[7px] uppercase tracking-[.1em]">Reject</button><button type="button" onClick={()=>moderate(review,"pending")} className="border border-black/10 px-3 py-2 text-[7px] uppercase tracking-[.1em]">Pending</button><button type="button" onClick={()=>remove(review)} className="ml-auto text-[7px] uppercase tracking-[.1em] text-[#cf1f2e]">Delete</button></div></article>)}</div>{!rows.length?<div className="border border-black/10 bg-[#f7f3ed] p-10 text-center font-[Georgia] text-[28px]">No reviews in this queue.</div>:null}</>;
}
